name: Typeset Check

on: pull_request
    
jobs:
  check_typeset:
    runs-on: ubuntu-latest
    name: Typeset check
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile Tex File
        id: compile_tex_file
        uses: hitsumabushi845/platex-action@main
        with:
          LATEX_FILE_NAME: "gas_slack_lecture_text.tex"

